import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const env = createEnv({
  server: {
    DATABASE_URL: z.string().url(),
    HUBSPOT_API_KEY: z.string().min(1),
    HUBSPOT_PORTAL_ID: z.string().min(1),
    RESEND_API_KEY: z.string().min(1),
    TURNSTILE_SECRET_KEY: z.string().min(1),
    NOTIFICATION_EMAIL: z.string(),
    FROM_EMAIL: z.string().email(),
    JWT_SECRET: z.string().min(32),
    ADMIN_EMAILS: z.string(),
    COMPANY_NAME: z.string().default("TensorWorks Pty Ltd"),
    COMPANY_ABN: z.string().default("84 544 119 830"),
    COMPANY_ADDRESS: z.string().default("Bendigo, Victoria, Australia"),
    REDIS_URL: z.string().optional(),
    REDIS_PASSWORD: z.string().optional(),
    ANTHROPIC_API_KEY: z.string().optional(),
    MONTHLY_AI_BUDGET_AUD: z.string().default("500"),
    MAILCHIMP_API_KEY: z.string().optional(),
    MAILCHIMP_SERVER_PREFIX: z.string().optional(),
    MAILCHIMP_AUDIENCE_ID: z.string().optional(),
    MAILCHIMP_FROM_NAME: z.string().default("TensorWorks"),
    MAILCHIMP_FROM_EMAIL: z.string().default("newsletter@tensorworks.com.au"),
    MAILCHIMP_REPLY_TO: z.string().default("hello@tensorworks.com.au"),
    MAILCHIMP_WEBHOOK_SECRET: z.string().optional(),
    BACKUP_S3_ENDPOINT: z.string().optional(),
    BACKUP_S3_BUCKET: z.string().optional(),
    BACKUP_S3_ACCESS_KEY: z.string().optional(),
    BACKUP_S3_SECRET_KEY: z.string().optional(),
  },
  client: {
    NEXT_PUBLIC_SITE_URL: z.string().url(),
    NEXT_PUBLIC_TURNSTILE_SITE_KEY: z.string().min(1),
    NEXT_PUBLIC_GA_ID: z.string().optional(),
  },
  runtimeEnv: {
    DATABASE_URL: process.env.DATABASE_URL,
    HUBSPOT_API_KEY: process.env.HUBSPOT_API_KEY,
    HUBSPOT_PORTAL_ID: process.env.HUBSPOT_PORTAL_ID,
    RESEND_API_KEY: process.env.RESEND_API_KEY,
    TURNSTILE_SECRET_KEY: process.env.TURNSTILE_SECRET_KEY,
    NOTIFICATION_EMAIL: process.env.NOTIFICATION_EMAIL,
    FROM_EMAIL: process.env.FROM_EMAIL,
    JWT_SECRET: process.env.JWT_SECRET,
    ADMIN_EMAILS: process.env.ADMIN_EMAILS,
    COMPANY_NAME: process.env.COMPANY_NAME,
    COMPANY_ABN: process.env.COMPANY_ABN,
    COMPANY_ADDRESS: process.env.COMPANY_ADDRESS,
    REDIS_URL: process.env.REDIS_URL,
    REDIS_PASSWORD: process.env.REDIS_PASSWORD,
    ANTHROPIC_API_KEY: process.env.ANTHROPIC_API_KEY,
    MONTHLY_AI_BUDGET_AUD: process.env.MONTHLY_AI_BUDGET_AUD,
    MAILCHIMP_API_KEY: process.env.MAILCHIMP_API_KEY,
    MAILCHIMP_SERVER_PREFIX: process.env.MAILCHIMP_SERVER_PREFIX,
    MAILCHIMP_AUDIENCE_ID: process.env.MAILCHIMP_AUDIENCE_ID,
    MAILCHIMP_FROM_NAME: process.env.MAILCHIMP_FROM_NAME,
    MAILCHIMP_FROM_EMAIL: process.env.MAILCHIMP_FROM_EMAIL,
    MAILCHIMP_REPLY_TO: process.env.MAILCHIMP_REPLY_TO,
    MAILCHIMP_WEBHOOK_SECRET: process.env.MAILCHIMP_WEBHOOK_SECRET,
    BACKUP_S3_ENDPOINT: process.env.BACKUP_S3_ENDPOINT,
    BACKUP_S3_BUCKET: process.env.BACKUP_S3_BUCKET,
    BACKUP_S3_ACCESS_KEY: process.env.BACKUP_S3_ACCESS_KEY,
    BACKUP_S3_SECRET_KEY: process.env.BACKUP_S3_SECRET_KEY,
    NEXT_PUBLIC_SITE_URL: process.env.NEXT_PUBLIC_SITE_URL,
    NEXT_PUBLIC_TURNSTILE_SITE_KEY: process.env.NEXT_PUBLIC_TURNSTILE_SITE_KEY,
    NEXT_PUBLIC_GA_ID: process.env.NEXT_PUBLIC_GA_ID,
  },
});
